### PR TITLE
Jack Croal 01592826 - Completed template exercise that involves the stack data structure

### PR DESCRIPTION
**Pull request by croaljack0**
## Solidity Stack Data Structure

I have implemented a template exercise that introduces the reader to slightly a more complex data structure: the stack. A Solidity list implementation is given and the reader is required to implement the remove() function of the stack.

Name: Jack Croal
CID: 01592826

### CODE REVIEW

**Comment by nud3l** [comment]
Please do not edit the MODIFY_ME.md! Add a separate file to commit your exercise.

**Comment by nud3l** [comment]
Please keep in mind that the language is called Solidity and not singularity :)

Last, I would extend the exercise to include also memory arrays. You will need to implement your own push and pop operations for this.

**Review by nud3l — CHANGES_REQUESTED** [review]
Do not edit MODIFY_ME.

**Comment by croaljack0** [comment]
Hi,
I have now created a new file for my tutorial (the example tutorial's .md file is no longer modified).
I have also corrected the spelling mistake and will start work on implementing memory arrays as mentioned above.
Thanks

**Pull request closed without merging**
