### PR TITLE
Rock Paper Scissors tutorial

### PR DESCRIPTION
**Pull request by bengunton**
A simple tutorial that teaches the user how to make a simple contract for a game of rock, paper, scissors. It also introduces the idea of using constructors with arguments.

One player will set up the contract with their chosen move using the constructor, and interacting with the contract through a challenge function allows another player to make their move.

### CODE REVIEW

**Review by nud3l — CHANGES_REQUESTED** [review]
This does not work in practice. Remember that all functions and storage on Ethereum or (most) other blockchains are visible to the entire world. In your contract, the first player will always lose because the second player can see the move and will win. You would need to use a commit and reveal scheme to solve this: [https://karl.tech/learning-solidity-part-2-voting/](https://karl.tech/learning-solidity-part-2-voting/)

**Comment by nud3l** [comment]
Can I please also have your name for grading?

**Comment by bengunton** [comment]
Thanks for the feedback, I think the issue is that I have made an incorrect assumption about how private variables work within the contracts. I will look into the commit and reveal scheme.

**Comment by bengunton** [comment]
My name is Benjamin Gunton, username bsg15.

**Pull request closed without merging**
