### PR TITLE
Wrote exercise for random behaviour in smart contracts.

### PR DESCRIPTION
**Pull request by danrobdean**
The exercise involves implementing a lottery. Since smart contracts are deterministic, this isn't as easy as it sounds!

### CODE REVIEW

**Comment by arthurgervais** [comment]
Interesting exercise. One limitation that you might want to describe is that you assume that all participants that committed a random value in form of a hash, will also reveal them at a later point in time.

**Comment by nud3l** [comment]
Hi Dominik here, I'm a TA in Arthur's course. Thanks for adding this exercise! I think it is a great example of how you can achieve random numbers on the blockchain. 

Could you please move the exercise to a separate file instead of the MODIFY_ME? We need to keep them in separate files, otherwise, we won't be able to have multiple contributions. We will add a note in the README of the repo.

Feedback to your solution:

- What I am missing a bit is the ability to submit value or tokens to win something in the lottery. That would be a nice extension. You could, for example, make the `provideRandomHash` function payable to achieve that.
- Users do not have an incentive to submit the hash as mentioned by Arthur before. You could add a deposit that users have to pay in order to submit a random hash. When they reveal the hash, they get their deposit back. Otherwise, it would be part of the lottery. You could further extend this by providing a time/block limit. For example, you could say the lottery ends in 2000 blocks. Every user then has 200 blocks time to submit their hash without getting their deposit destroyed.
- Using arrays in Solidity/EVM can be a bit problematic. Assume you have a very very large number of participants. In your `getWinner` function, you loop through every participant. Assuming your gas cost for the number of operations will exceed the global gas limit (which is likely for a very large number of participants), you will never have a winner. So you might want to set a limit to the number of participants or think about a different data structure/algorithm to determine the winner.

**Comment by danrobdean** [comment]
Thanks for the feedback!

I have added a limit to the number of entrants in the exercise, to prevent the list size from being unbounded (I chose 100 as an arbitrary value).

With regards to the deposit, I intended to include a note about it in the exercise, but forgot to do this originally. I've added the note now explaining the issue and why a deposit would make sense. I did not add it to the exercise code as I intended for the code to only cover the process which is necessary for obtaining random data in a smart contract. Having to add code for handling deposits would take the focus away from random number processing in my opinion (although this is obviously subjective). I also did not add a payout for the winner for the same reason.

**Comment by nud3l** [comment]
Could you please make sure not to delete the MODIFY_ME.md in your pull request?

**Review by nud3l — CHANGES_REQUESTED** [review]
Do not remove MODIFY_ME

**Comment by danrobdean** [comment]
I've added back the MODIFY_ME file, it's renamed to EXAMPLE.md to match the updated example file

**Pull request closed without merging**
