### PR TITLE
Two signature contract

### PR DESCRIPTION
**Pull request by ojroques**
This exercise implements a basic two signature contract where two participants have to agree on a payment before it is executed. Unfortunately I couldn't manage to make the verification work for the first part so I haven't tried writing checks for the last two parts.

Name: Olivier Roques
CID: 01574211

### CODE REVIEW

**Review by nud3l — CHANGES_REQUESTED** [review]
Please don't update the Makefile

**Review by nud3l — CHANGES_REQUESTED** [review]
Please do not delete MODIFY_ME

**Review by nud3l — COMMENTED** [review]
Thanks for submitting this. I think the contract could be a bit improved. A general thing is that I need to commit to one recipient over the complete lifetime of the contract. It would be much better to not have only a single recipient or at least have the option to update the recipient (including the necessary checks for the signatures). You also don't specify amounts to transfer and your `register` function is not `payable`, which means that the contract balance will be 0.

Also, your contract has an issue with reentrancy. Your `action` function should first set the `registered` parameters to false and then transfer. Otherwise, party A or B could reenter the function.

**Comment by ojroques** [comment]
Thank you for your feedback. I've reverted changes to Makefile and renamed the exercise to MODIFY_ME.md. I've also made `register()` payable and fixed the reentrancy issue. I wanted to keep the exercise as simple as possible as I'm not experienced with Solidy at all, so that's why there's so few features.

**Pull request closed without merging**
